### ISSUE TITLE
[BUG] Lua error

### ISSUE THREAD

**Issue by Q8BoRashed** [TLDRMissions/TLDRMissions#288]
### Copy/paste the Lua error here

1x [ADDON_ACTION_BLOCKED] AddOn 'TLDRMissions' tried to call the protected function 'CompactRaidFrame2:ClearAllPoints()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `ClearAllPoints'
[string "@FrameXML\FlowContainer.lua"]:157: in function `FlowContainer_DoLayout'
[string "@FrameXML\FlowContainer.lua"]:17: in function `FlowContainer_ResumeUpdates'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:185: in function `CompactRaidFrameContainer_LayoutFrames'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:130: in function `CompactRaidFrameContainer_TryUpdate'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:57: in function `CompactRaidFrameContainer_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

1x [ADDON_ACTION_BLOCKED] AddOn 'TLDRMissions' tried to call the protected function 'CompactRaidFrame4:Show()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `Show'
[string "@FrameXML\CompactUnitFrame.lua"]:378: in function `CompactUnitFrame_UpdateVisible'
[string "@FrameXML\CompactUnitFrame.lua"]:309: in function <FrameXML\CompactUnitFrame.lua:307>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAll'
[string "@FrameXML\CompactUnitFrame.lua"]:116: in function <FrameXML\CompactUnitFrame.lua:45>

Got 2 errors. I'm very new to this so hope I've done the format correctly. Will provide more info if needed.

**Comment by teelolws** [comment]
Some other addon that uses Ace3 is causing this. I don't make any calls to CompactRaidFrame.

Do you remember what you were doing when the error happened? Turn my addon off and do it again.

**Comment by Q8BoRashed** [comment]
I was just in a normal LFG dungeon. Not sure what's specifically causing it. I will try reproducing it somehow and make a video of when it triggers with enabling/disabling the addon and see if it goes away. I will post back if I can make it happen. Thank you

**Comment by Q8BoRashed** [comment]
I recorded an LFG run and I had 1 error constantly happening and another that happened exactly as the 1st boss dies. Disabling TL;DR seemed to stop both errors from occurring, but reenabling the addon and killing the last boss I didn't get the latter error again just once. Here's a video and I will mention timestamps of the important parts below: [https://www.youtube.com/watch?v=FpRqZt9dZ3U](url)

Start to end we have this error constantly being spammed: 
**Error #1**
`570x FrameXML\CompactUnitFrame.lua:1122: Attempt to access forbidden object from code tainted by an AddOn
[string "=[C]"]: in function `Hide'
[string "@FrameXML\CompactUnitFrame.lua"]:1122: in function `CompactUnitFrame_UpdateClassificationIndicator'
[string "@FrameXML\CompactUnitFrame.lua"]:1380: in function <FrameXML\CompactUnitFrame.lua:1374>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML\CompactUnitFrame.lua"]:96: in function <FrameXML\CompactUnitFrame.lua:45>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}`

At some point I close the BugSnatcher window and mouseover the minimap icon because I just assumed the other error wasn't happening because of the window open. I open it again at the 1st boss. 

Around 1:39 the boss dies and the 2nd error appears:
**Error #2**
`1x [ADDON_ACTION_BLOCKED] AddOn 'TLDRMissions' tried to call the protected function 'CompactRaidFrame1:ClearAllPoints()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `ClearAllPoints'
[string "@FrameXML\FlowContainer.lua"]:157: in function `FlowContainer_DoLayout'
[string "@FrameXML\FlowContainer.lua"]:17: in function `FlowContainer_ResumeUpdates'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:185: in function `CompactRaidFrameContainer_LayoutFrames'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:130: in function `CompactRaidFrameContainer_TryUpdate'
[string "@Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:57: in function `CompactRaidFrameContainer_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals:
Skipped (In Encounter)`

3:07 I turn off the addon and wipe the errors from BugSack.

5:26 2nd boss dies and so far neither error #1 or #2 are showing up. I enable the addon again from this point forward and the 1st error starts spamming again.

6:58 3rd boss dies and error #2 shows up again.

8:20 last boss dies and error #2 doesn't seem to show up as when I cycle between errors, it shows as 1x and I assume this means it happened once which was on the 3rd boss (and on the 1st boss previous but I had wiped the errors since then.)

I have to note that since I wiped the BugSack addon midway the error that's appearing on the bosses might be different than what I pasted above. I apologize if that's the case.

I have attached the taint.log.

Hope this was helpful in any way.



[taint.log](https://github.com/TLDRMissions/TLDRMissions/files/8790720/taint.log)

**Comment by teelolws** [comment]
Get the update I released about an hour ago. I've isolated all the libraries. If some other addon is causing it, the blame will move to them. If its mine, then I have a serious problem.

**Comment by Q8BoRashed** [comment]
Will do. I'll post an update here when I can after applying the update.

**Comment by Q8BoRashed** [comment]
Still having the exact same issues after update. Error #1 constantly spammed and Error #2 shows up on boss. Disabling only TL;DR stopped any furhter errors from occuring. Maybe it is a weird interaction with the addons I have I hope someone else with the same issues can post here maybe provide you more info. Best of luck.

**Comment by teelolws** [comment]
Whats that addon you're running for your raid frames?

**Comment by Q8BoRashed** [comment]
Raid frames are Blizzard default frames. I can provide full list of addons if needed.

**Comment by teelolws** [comment]
How did you move it to the middle of the screen like that?

**Comment by Q8BoRashed** [comment]
I assume you're talking about the party frames on the left side of the screen? If it's the small bars on the center of the screen slightly left of the WeakAura for the mage abilities then that's just the interrupt bar from OmniCD.

**Comment by teelolws** [comment]
Yeah the party frames on the left. How did you move them from where Blizzard normally puts them (topleft)?

And what about the debuffs and cast bars to the left of the frames. Is that an addon?

**Comment by Q8BoRashed** [comment]
Ah I see. I moved them just using the default lock/unlock feature provided by expanding the interface to the far left of the screen (I believe it's called the raid profiles.) 

For the cast bars it's JaxPartyBars. For the debuffs that show on the party frames themselves it's both BigDebuffs and a WA (Dungeon - Targeted Spells https://wago.io/BFADungeonTargetedSpells/68.) 

For the cooldown tracker left of the bars it's OmniCD as well.

**Comment by teelolws** [comment]
I'm trying to recreate your UI so I can get the error, but not having much luck. Are you willing to send me your entire UI? Both your addons folder, and your settings in your WTF folder. I can give you access to a private repository if you don't want to share them publicly.

**Comment by Q8BoRashed** [comment]
Sure. So you'd want the addons folder and also the entire WTF folder or only parts of it?

**Comment by teelolws** [comment]
The parts for the account of the character you had that problem with. I'll just rename them to my character and test it

**Comment by teelolws** [comment]
Sent you an invite for access to https://github.com/TLDRMissions/tainterrors. You can upload them into the repository, or make an issue, your choice. Doesn't matter, I'll delete them when we're done.

**Comment by Q8BoRashed** [comment]
Sure uploading now.

**Comment by Q8BoRashed** [comment]
I can't upload the Interface folder because it says it's a lot files. Any way around this?

**Comment by teelolws** [comment]
.zip it up

**Comment by teelolws** [comment]
![image](https://user-images.githubusercontent.com/49792789/170818138-7f439013-f335-4a84-95e0-e607963d4343.png)
 TIL Github has a 25MB filesize limit.

Can you split it into a couple different .zips?

**Comment by Q8BoRashed** [comment]
Working on it.

**Comment by Q8BoRashed** [comment]
Done. I'm entirely new to this so hope it works properly.

**Comment by teelolws** [comment]
> EDIT: I also want to add that I use a customs icon pack which I didn't include because they were around 1.1gb in size. If you'd like I can provide the link to download them.

Nah that shouldn't matter. I'll get green boxes but whatever!

**Comment by Q8BoRashed** [comment]
Sweet. Back to watching the Johnny Depp trial then )). Hit me up if you need anything else.

**Comment by teelolws** [comment]
Sorry, I also need your account-wide saved variables. Its under WTF\Account\ your wow account\SavedVariables like this:
![image](https://user-images.githubusercontent.com/49792789/170818733-39809a37-fb32-4bff-b8ea-4ab7c6343188.png)

**Comment by Q8BoRashed** [comment]
Done.

**Comment by teelolws** [comment]
Heres my experience so far, running your exact UI.

Same error, but it blames BigDebuffs:
![image](https://user-images.githubusercontent.com/49792789/170819480-9fbe1537-c46f-456a-beba-4871839d1428.png)

A quick look at the BigDebuffs issues page, looks like others are having the same problem: https://github.com/jordonwow/bigdebuffs/issues/384

The error is being intermittent, though. With all addons still on, sometimes it pops, sometimes it doesn't. Trying to find a way to make it consistent.
